-- 1. PROFILES (Extends Supabase Auth)
-- This table automatically links to the auth.users table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. SUBSCRIPTION PLANS
-- Static table to define your 3 tiers
create table public.plans (
  id serial primary key,
  name text not null, -- e.g., 'Free', 'Starter', 'Pro'
  price_monthly integer not null, -- Price in cents (e.g., 2900 for $29.00)
  daily_scrape_limit integer not null, -- e.g., 5, 100, 1000
  features jsonb -- Store extra feature flags here
);

-- Seed your 3 plans
insert into public.plans (name, price_monthly, daily_scrape_limit) values
('Free', 0, 5),
('Starter', 2900, 100),
('Pro', 9900, 1000);

-- 3. USER SUBSCRIPTIONS
-- Connects a user to a plan and payment status
create table public.subscriptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  plan_id integer references public.plans(id) not null,
  status text check (status in ('active', 'past_due', 'canceled', 'trialing')),
  current_period_end timestamp with time zone,
  stripe_customer_id text, -- Link to Stripe/LemonSqueezy
  stripe_subscription_id text,
  created_at timestamp with time zone default now()
);

-- 4. SCRAPING JOBS (The "Hash" Table)
-- This stores the request metadata and the unique hash
create table public.scraping_jobs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  job_hash text not null unique, -- THE UNIQUE HASH you requested
  target_url text not null,
  status text check (status in ('pending', 'processing', 'completed', 'failed')),
  row_count integer default 0, -- How many items were found
  created_at timestamp with time zone default now()
);

-- 5. SCRAPED DATA STORE
-- Stores the actual data. We use JSONB so you can store ANY structure.
create table public.scraped_data (
  id bigint generated by default as identity primary key,
  job_hash text references public.scraping_jobs(job_hash) on delete cascade not null,
  data jsonb not null, -- The actual scraped product/info
  scraped_at timestamp with time zone default now()
);

-- 6. PAYMENT HISTORY (Audit Log)
create table public.invoices (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) not null,
  amount_paid integer not null,
  currency text default 'usd',
  status text,
  invoice_pdf_url text,
  created_at timestamp with time zone default now()
);